#!/bin/bash


#How to collect results:
#./run_mcpat.sh /scratch/ishitac/GPU_killer/gem5-GPU_killer/sparse_matrix/mcpat_analysis/Dynamic_1pThread_400_80Per_sparse_ROB256 Dynamic_1pThread_400_80Per_sparse_ROB256
#./run_mcpat.sh /scratch/ishitac/GPU_killer/gem5-GPU_killer/sparse_matrix/mcpat_analysis/pthreadDynamic_AllW6_400_80Per_sparse_ROB256 pthreadDynamic_AllW6_400_80Per_sparse_ROB256
#./run_mcpat.sh /scratch/ishitac/GPU_killer/gem5-GPU_killer/sparse_matrix/mcpat_analysis/pthreadDynamic_2S4W_400_80Per_sparse_ROB256 pthreadDynamic_2S4W_400_80Per_sparse_ROB256
#./run_mcpat.sh /scratch/ishitac/GPU_killer/gem5-GPU_killer/sparse_matrix/mcpat_analysis/Dynamic_2pThread_400_80Per_sparse_ROB256 Dynamic_2pThread_400_80Per_sparse_ROB256
#./run_mcpat.sh /scratch/ishitac/GPU_killer/gem5-GPU_killer/sparse_matrix/mcpat_analysis/Dynamic_3pThread_400_80Per_sparse_ROB256 Dynamic_3pThread_400_80Per_sparse_ROB256

umask 0002
echo $@

#CFG=$3
#USER_ID=$1
WORK_DIR=$1
NAME=$2

#!/bin/bash

# Check if the input stats.txt file was provided as argument
if [ -z "$1 $2" ]; then
    echo "Usage: $0 /path/to/stats.txt small_name"
    exit 1
fi

# Define variables for file paths
STATS_FILE="$1/stats.txt"
OUTPUT_FILE="small_txt/${NAME}_small.txt"  # Output file for pruned stats
CONFIG_FILE="$1/config.json"
TEMPLATE_FILE="Gem5McPatParser/templates/template_arm.xml"
OUTPUT_DIR="Gem5McPatParser"

# Step 1: Prune stats file using Python script
echo "Pruning stats file..."
python prune_stats.py "$STATS_FILE" "$OUTPUT_FILE"

# Step 2: Run Gem5McPATParser with the pruned stats file and config
echo "Running Gem5McPatParser..."
python3 Gem5McPatParser/Gem5McPATParser_updated.py -c "$CONFIG_FILE" -s "$OUTPUT_FILE" -t "$TEMPLATE_FILE" -o xml_results/"$NAME".xml &> out

# Step 3: Run mcpat with the output XML file generated by Gem5McPatParser
echo "Running mcpat..."
./mcpat/mcpat_orig/mcpat -infile xml_results/"$NAME".xml -print_level 5 > mcpat_results/"$NAME"_mcpat.out

#echo "Analysis completed. Output is in '$1.out'."

